repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: debug-statements
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: no-commit-to-branch
    - id: flake8
      args: ["--exclude=docs/*,*migrations*", "--ignore=E501,W503,E203"]

-   repo: local
    hooks:
    -   id: pipenv-check
        name: Pipenv Check
        entry: pipenv check
        language: system
        files: Pipfile
        verbose: false
        pass_filenames: false

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
      args: ["--check-only", "--diff"]
      additional_dependencies: ["toml"]

- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
    - id: black
